<?php

use Drupal\node\Entity\Node;

/**
 * Implements hook_entity_presave().
 */
function summit_entities_entity_presave(Drupal\Core\Entity\EntityInterface $entity) {
  // Split the term name (i.e., an author's name) in a very simplistic way
  // and populate the appropriate fields in the term entity.
  if ($entity->getEntityTypeId() == 'taxonomy_term' && $entity->bundle() == 'author') {
    list($last_name, $given_name) = explode(',', $entity->getName());
    $entity->set('field_given_name', trim($given_name));
    $entity->set('field_last_name', trim($last_name));
  }
}

/**
 * Implements hook_entity_insert().
 */
function summit_entities_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {
  // Create an author page, assigning ownership to the new user.
  // Defaults on this content type should be set to not publish, not promote.
  if ($entity->getEntityTypeId() == 'user') {
    $uid = $entity->id();
    $node = Node::create(['type' => 'author_page']);
    $node->set('title', 'Enter name in firstname lastname format');
    $node->set('uid', $uid);
    $node->enforceIsNew();
    $node->save();
  }
}

